### ISSUE TITLE
[Bug] Application crashes when saving a ranked game with no deck selected

### ISSUE THREAD

**Issue by ThatNorthernMonkey** [MarioZG/elder-scrolls-legends-tracker#1]
Hey, woke up this morning and opened the app to start playing. The overlay popped up but the main screen stayed in the background, so (without thinking) I started using the overlay, but if you don't specifically select the deck on the main screen before interacting with the overlay then it crashes when you select 'Victory' or 'Defeat'. A little bit counter-intuitive because the overlay pops up at the front, so some constraints are required to force the user to pick the deck they're using before the overlay pops up. Thanks for the app though, really nice!

[crash201612130703.txt](https://github.com/MarioZG/elder-scrolls-legends-tracker/files/648194/crash201612130703.txt)

**Comment by MarioZG** [comment]
You need just active deck and opponent class to save game.
I'll fix crash and think about better feedback what is missing.
