### ISSUE TITLE
Exe file

### ISSUE THREAD

**Issue by Vampiricangeluk** [MarioZG/elder-scrolls-legends-tracker#13]
Hi, I can't seem to find the exe file for this tracker. can you tell me where it is please?

**Comment by MarioZG** [comment]
Hi, it's in zip file attached to release - [ ESLTracker_0.6.8.zip](https://github.com/MarioZG/elder-scrolls-legends-tracker/releases/download/v0.6.8/ESLTracker_0.6.8.zip). Just unzip and run esltracker.exe

**Comment by Vampiricangeluk** [comment]
Thanks Mario.   The tracker has opened the game for me.. but doesn't seem to connect or recognise my game is running its open and played 2 games but nothing, doesnt seem to be connected even though its open and the game is open..any ideas how to fix it? can't see whats wrong

**Comment by MarioZG** [comment]
Hi, it's not automated. You''ll have overlay window on game screen, with option to add games manually. If it's not visible please check option in main menu: overlays -> add game/rewards/pack option - it should make it visible then
