### ISSUE TITLE
Session statistics 

### ISSUE THREAD

**Issue by MarioZG** [MarioZG/elder-scrolls-legends-tracker#3]
One of the suggestion was to add session stats. My thoughts are to add another overlay window/panel that you can move aroiund, with configurable content (few options to choose from).

What kind of stats would you like to see? Obviously win-loss, but are there any others that you would like to display on screen during game?

Also for which period of time would you like to the include stats? Time since application started? Last x minutes? last x games? Last x games with current deck? 

Any suggestions will be appreciated, and likely implemented!

**Comment by KiloJKilo** [comment]
Hi, I think an overall damage received/dealt stat would be interesting. Also, when analyzing deck performance relative to other decks, it would be interesting to track abilities damage. For example, at the end of a match, I'd like to see how my card's abilities stacked up against the other player. Inversely, I'd like to see how abilities like opponents pilfer or lethal affected me. I want to know how much card/face health I lost from those abilities, or how many cards were lost. Stuff like that.

**Comment by MarioZG** [comment]
Hi, that sounds like very interesting and useful set of stats, unfortunately this would be very hard to track manually. I'll think about adding some fields, that you might fill at the end of game. 
One option would be to put this in standardised notes to game and then process it in excel (i think I'll finally add data export option in near future).

**Comment by KiloJKilo** [comment]
I wonder if it's possible to put a form per each slot of the lane. In that form you could put a series of jspinners with text box (for a note) for each ability (pilfer, lethal, raw damage, other...). On the opponents side, when you deal damage and/or ability, you can use like a jspinner to indicate the damage and a text box to indicate removal, etc. On your side, it's the same thing, but you're logging the damage dealt to you. The more I write this, the more I feel like it would be distracting to log during game play, and downright obnoxious to log when cards are really flying and moving around so I guess it's probably only useful in matches where you are testing decks against a friend. However, using some sort of screen recognition on the match history area could automate this completely, which may or may not be out of the scope here. I remember the days of auto-players for online games that could scan the screen and all that and then play for you, I don't know how it is done tho. Maybe I'll revisit this concept after I've played more for additional ideas.

**Comment by MarioZG** [comment]
I do agree, it would be more like playing excel than TESL play with all this spinners and logs :)
I did look at screen recognition, but I'm not sure if this would be reliable way to log things (detection of targets and capturing all moves would be quite difficult)

All hopes on Bethesda producing actual reliable text log!

**Comment by MarioZG** [comment]
Added in [https://github.com/MarioZG/elder-scrolls-legends-tracker/releases/tag/v0.7.0](v0.7)
