### ISSUE TITLE
'Run game' from system tray fails when Bethesda Launcher already open

### ISSUE THREAD

**Issue by tzerk** [MarioZG/elder-scrolls-legends-tracker#6]
Titel says it all: when the Bethesda Launcher is open and you want to start the game via the right-click menu on the system tray icon you get the following error message:

> [...] Unable to verify latest before launching. Please check network connection and tray again. [...]

The "Run game" option in the main window of the tracker works fine, however. The system tray option only works when the Bethesda Launcher is closed.

**Comment by MarioZG** [comment]
I believe this is how launcher behaves and i won't  be able to do anything about it. 

On my machine in similar scenario (launcher in background), when i use game shortcut (not launcher) to start game it results in same error.

Would you be able to confirm if running via game shortcut result in same error?

**Comment by tzerk** [comment]
I see, but I have to admit that the behaviour is even more complicated than previously stated. I haven't found a clear pattern as to why it works sometimes and sometimes not. I can definitely confirm that the error does also appears when using the "Run game" option in the main window or using the game shortcut; at least under some specific circumstances. I will close this issue as this is most likely not something you could fix. Thanks for the response and a Happy New Year!

**Comment by MarioZG** [comment]
I'll reopen this. I cannot fix, but I should be able to check if launcher is running and at least warn user :)

Thanks a lot for a feedback and 100% win ratio New Year to you!

**Comment by MarioZG** [comment]
Has been some time but seems like Bethesda fixed the issue in launcher. With latest release, it will start game, even when luncher is running.
