### ISSUE TITLE
Feature Request: Filter Statistics by Deck

### ISSUE THREAD

**Issue by tzerk** [MarioZG/elder-scrolls-legends-tracker#7]
I really like the "Games analysis" window with the summaries presented with Live Charts. Currently, you are able to filter by game type (ranked or casual) and by date, but I would be interested in also filtering by a specific deck. Especially the "Games summary" with % win rate when played first or second gets easily watered down due to some decks I experimented with. Most of the time I am more interested in the stats of a specific deck rather than overall performance, however.

**Comment by MarioZG** [comment]
The whole screen will be re-worked after I'll add deck versions (should be 2-3 releases from now). I'll keep in mind to include 1st/2nd win ratio on deck level.

**Comment by MarioZG** [comment]
I have added 1st/2nd ratio for each deck and deck version. 

I still need improve this screen, but you should be able to get data now.
