### ISSUE TITLE
Ranked progress

### ISSUE THREAD

**Issue by theswoderman** [MarioZG/elder-scrolls-legends-tracker#9]
Ranked progress has stopped displaying.  Used to be able to look at the graph but as of yesterday it doesn't load any data even though I've been inputting my rank  Just shows up as a blank graph
![ranked](https://cloud.githubusercontent.com/assets/24849004/22321205/a13531da-e347-11e6-8e45-4ddfb08b240d.png)

**Comment by MarioZG** [comment]
Hi,

Does it display anything when you expand date filter (to "This month" or All)?

**Comment by theswoderman** [comment]
i can't get it to display any data for any of the time ranges

**Comment by MarioZG** [comment]
did you updated application or get any error before it happened? Can you send me data file (c:\Users\<your username>\AppData\Roaming\ESLTracker\data.xml)

**Comment by theswoderman** [comment]
I don't think I updated before this happened, definitely didn't get an error.  Github won't let me send ou the data file, says the file isn't supported

**Comment by MarioZG** [comment]
Are all other stats ok?

If you get latest version of app, in about window there is link to direct email address (don't want to put it here because of bots) - send the file there.

**Comment by theswoderman** [comment]
The other stats were fine.  I'm not sure hat the issue was but I just deleted all the files and redownloaded the program and everything seems to be working now.  Have to start from scratch with my data but it's not a big deal.  I must have accidentally messed with something on my side.  Thanks for the help!

**Comment by MarioZG** [comment]
no worries. Sorry abut the lost data though. In folder with data.xml  there are daily backups, if something will go wrong again, it might be worth restoring backup as data.xml (while application is NOT running) to see if it helps.
